# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

#project 'path/to/Project.xcodeproj'

source 'https://github.com/CocoaPods/Specs.git'

target 'CCSQLiteiOSDemo' do
	pod 'CCSQLite'
end

target 'CCSQLiteDataiOS' do
    pod 'CCSQLite'
end

target 'CCSQLiteOSXDemo' do
	pod 'CCSQLite'
end


target 'CCSQLiteDatamacOS' do
    pod 'CCSQLite'
end
