# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'CCSQLiteiOSDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CCSQLiteiOSDemo
	pod 'CCSQLite', path:'..'
end

target 'CCSQLiteOSXDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CCSQLiteOSXDemo
	pod 'CCSQLite', path:'..'
end
